version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment: 
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://rabbitmq
      - POSTGRES_HOST=34.83.179.230
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=miso4204
      - POSTGRES_DB=miso4204db
      - BATCH_IP=10.138.0.3
      - BATCH_PORT=5005
    volumes:
    - /nfs/general:/nfs/general 
