version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_app_network
    depends_on:
      - db
    volumes:
    - /nfs/general:/nfs/general 

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: miso4204
      POSTGRES_DB: miso4204db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@uniandes.edu.co
      PGADMIN_DEFAULT_PASSWORD: miso4204
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_app_network

networks:
  my_app_network:
    external: true

volumes:
  pgdata: