version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_app_network
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=miso4204
      - POSTGRES_DB=miso4204db

  celery:
    build: .
    command: celery -A src.celery.celery_config.celery_app worker --loglevel=info
    working_dir: /src
    depends_on:
      - rabbitmq
    environment: 
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq//
      - CELERY_RESULT_BACKEND=rpc://rabbitmq
    networks:
      - my_app_network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge
    ipam:
      driver: default