version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: miso4204
      POSTGRES_DB: miso4204db
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@uniandes.edu.co
      PGADMIN_DEFAULT_PASSWORD: miso4204
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://admin:miso4204@db:5432/miso4204db
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: ["/app/wait-for-it.sh", "db:5432", "--", "flask", "run", "--host=0.0.0.0"]