version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_app_network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: trayectosuser
      POSTGRES_PASSWORD: mystrongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge

volumes:
  pgdata:
